### ISSUE TITLE
Positions all lost for Microscope saved in Electron 

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolOmero#4]
When tesm_mma_el_103019.json that had been saved in v0016-1 in Electron was imported into OMERO the positions of components were distributed onto an enormous canvas all over the places

<img width="1311" alt="Issue_#1_2" src="https://user-images.githubusercontent.com/4050585/67921722-02542c80-fb7f-11e9-861d-7024a0afc1b9.png">

<img width="1311" alt="Issue_#1" src="https://user-images.githubusercontent.com/4050585/67921584-9ffb2c00-fb7e-11e9-9cf7-277bec326e67.png">

**Comment by strambc** [comment]
Also a lot of different components lost the validation status (red box reappeared)

**Comment by Akramhar** [comment]
should be fixed
